/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aluguelautomoveis.controllerview;

import com.aluguelautomoveis.model.Aluguel;
import com.aluguelautomoveis.model.Automovel;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.aluguelautomoveis.model.dao.AluguelDao;
import com.aluguelautomoveis.model.dao.AutomovelDao;


/**
 *
 * @author Locadora de Veículo
 */
public class FormConsultaLocacao extends javax.swing.JFrame {

  Automovel automovel = null;
  Aluguel aluguel = null;
    
    public FormConsultaLocacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jbbuscartodos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbbuscarauto = new javax.swing.JButton();
        jtnumaluguel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtlocacoes = new javax.swing.JTable();
        jbfinalizarlocacao = new javax.swing.JButton();
        jbmulta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consuta Locações");
        setMinimumSize(new java.awt.Dimension(800, 700));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Locações"));

        jbbuscartodos.setText("Buscar todos");
        jbbuscartodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbuscartodosActionPerformed(evt);
            }
        });

        jLabel1.setText("Número Aluguel");

        jbbuscarauto.setText("Buscar por número");
        jbbuscarauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbuscarautoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtnumaluguel))
                .addGap(6, 6, 6)
                .addComponent(jbbuscarauto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbbuscartodos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbbuscarauto)
                    .addComponent(jbbuscartodos)
                    .addComponent(jtnumaluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jtlocacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Cliente", "CPF", "Habilitação", "Marca", "Modelo", "Placa", "Valor Locação", "Data Locação", "Data Devolução"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtlocacoes.getTableHeader().setReorderingAllowed(false);
        jtlocacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtlocacoesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtlocacoes);
        if (jtlocacoes.getColumnModel().getColumnCount() > 0) {
            jtlocacoes.getColumnModel().getColumn(0).setResizable(false);
            jtlocacoes.getColumnModel().getColumn(1).setResizable(false);
            jtlocacoes.getColumnModel().getColumn(2).setResizable(false);
            jtlocacoes.getColumnModel().getColumn(3).setResizable(false);
            jtlocacoes.getColumnModel().getColumn(4).setResizable(false);
            jtlocacoes.getColumnModel().getColumn(5).setResizable(false);
            jtlocacoes.getColumnModel().getColumn(7).setResizable(false);
            jtlocacoes.getColumnModel().getColumn(8).setResizable(false);
            jtlocacoes.getColumnModel().getColumn(9).setResizable(false);
        }

        jbfinalizarlocacao.setText("Finalizar Locação");
        jbfinalizarlocacao.setEnabled(false);
        jbfinalizarlocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbfinalizarlocacaoActionPerformed(evt);
            }
        });

        jbmulta.setText("Calcular Multa");
        jbmulta.setEnabled(false);
        jbmulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmultaActionPerformed(evt);
            }
        });

        jButton1.setText("Gerar Nota Fiscal");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sair");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbfinalizarlocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbmulta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbfinalizarlocacao)
                    .addComponent(jbmulta)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbbuscartodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbuscartodosActionPerformed
  limparTabela();
        jtnumaluguel.setText("");
        
        ArrayList<Aluguel> lista = AluguelDao.getTodosAlugueis();
        
        DefaultTableModel modelo = (DefaultTableModel)jtlocacoes.getModel();
        
        if (!lista.isEmpty())
        {
            
            for(int i=0;i<lista.size();i++)
            {
              
                modelo.addRow(lista.get(i).getAluguelo());
            
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Nenhuma Locação Cadastrada!","ATENÇÃO!",JOptionPane.ERROR_MESSAGE);
            // TODO add your handling code here:
    }//GEN-LAST:event_jbbuscartodosActionPerformed

    private void jbbuscarautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbuscarautoActionPerformed
limparTabela();
if (jtnumaluguel.getText().isEmpty()){
    JOptionPane.showMessageDialog(null,"Digite o número da Locação!");
    jtnumaluguel.requestFocus(true);
}
else
{
 Aluguel aluguel = AluguelDao.getAluguel(Double.parseDouble(jtnumaluguel.getText()));
DefaultTableModel modelo = (DefaultTableModel)jtlocacoes.getModel();
if (aluguel != null)
{
    modelo.addRow(aluguel.getAluguelo());
} 
else
    JOptionPane.showMessageDialog(null,"Locação Inexistente!\n Não foi possível encontrar a locação especificado!","Atenção",JOptionPane.ERROR_MESSAGE);
      
    }//GEN-LAST:event_jbbuscarautoActionPerformed
    }
    private void jbfinalizarlocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbfinalizarlocacaoActionPerformed
int linha = jtlocacoes.getSelectedRow();
double numero = ((Double)jtlocacoes.getModel().getValueAt(linha,0));
aluguel = AluguelDao.getAluguel(numero);
aluguel.getAutomovel().Devolver();
automovel = aluguel.getAutomovel();
AutomovelDao.atualizarAutomovel(automovel);
AluguelDao.ConfirmaDevolucao(aluguel.getNumero());
JOptionPane.showMessageDialog(null,"Locação Finalizada com Sucesso!!!");
limparTabela();
jbfinalizarlocacao.setEnabled(false);
jbmulta.setEnabled(false);
jButton1.setEnabled(false);
    }//GEN-LAST:event_jbfinalizarlocacaoActionPerformed

    private void jbmultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmultaActionPerformed
int linha = jtlocacoes.getSelectedRow();
double numero = ((Double)jtlocacoes.getModel().getValueAt(linha,0));
aluguel = AluguelDao.getAluguel(numero);
Date hoje = new Date();
aluguel.diasMulta(aluguel.getDatadevolucao(),hoje);
aluguel.calcularMulta();
if (aluguel.getMulta()<=0){
    JOptionPane.showMessageDialog(null,"Não existe Multa para esta locação!!!");
}
else{
JOptionPane.showMessageDialog(null,"Valor da Multa: "+aluguel.getMulta());}
    }//GEN-LAST:event_jbmultaActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jtlocacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtlocacoesMouseClicked
if (jtlocacoes.getSelectedRow()!= -1){
                    jbfinalizarlocacao.setEnabled(true);
                    jbmulta.setEnabled(true);
                    jButton1.setEnabled(true);
     } else 
     {
         JOptionPane.showConfirmDialog(null,"Selecione uma Locação!");
         
     }        // TODO add your handling code here:
    }//GEN-LAST:event_jtlocacoesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
FormNotaFiscal fnf = new FormNotaFiscal();
fnf.setVisible(true);
int linha = jtlocacoes.getSelectedRow();
double numero = ((Double)jtlocacoes.getModel().getValueAt(linha,0));
aluguel = AluguelDao.getAluguel(numero);
FormNotaFiscal.aluguel  = aluguel;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked
    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConsultaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConsultaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConsultaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConsultaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConsultaLocacao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbbuscarauto;
    private javax.swing.JButton jbbuscartodos;
    private javax.swing.JButton jbfinalizarlocacao;
    private javax.swing.JButton jbmulta;
    private javax.swing.JTable jtlocacoes;
    private javax.swing.JTextField jtnumaluguel;
    // End of variables declaration//GEN-END:variables

  private void limparTabela()
    {
        DefaultTableModel modelo = (DefaultTableModel)jtlocacoes.getModel();
        for (int i = jtlocacoes.getRowCount() -1; i >= 0; --i)
        {
            modelo.removeRow(i);
        }
        
    }

}
