/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aluguelautomoveis.controllerview;

import com.aluguelautomoveis.model.AluguelBean;
import com.aluguelautomoveis.model.AutomovelBean;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.aluguelautomoveis.model.dao.AluguelDao;
import com.aluguelautomoveis.model.dao.AutomovelDao;

/**
 *
 * @author Locadora de Veículo
 */
public class FormConsultaLocacao extends javax.swing.JFrame {

    AutomovelBean automovel = null;
    AluguelBean aluguel = null;

    public FormConsultaLocacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        buttonBuscarTodos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonBuscarPorNumero = new javax.swing.JButton();
        textFieldNumeroAluguel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLocacoes = new javax.swing.JTable();
        buttonFinalizarLocacao = new javax.swing.JButton();
        buttonCalcularMulta = new javax.swing.JButton();
        buttonGerarNotaFiscal = new javax.swing.JButton();
        buttonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consuta Locações");
        setMinimumSize(new java.awt.Dimension(800, 700));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Locações"));

        buttonBuscarTodos.setText("Buscar todos");
        buttonBuscarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarTodosActionPerformed(evt);
            }
        });

        jLabel1.setText("Número Aluguel");

        buttonBuscarPorNumero.setText("Buscar por número");
        buttonBuscarPorNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarPorNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldNumeroAluguel))
                .addGap(6, 6, 6)
                .addComponent(buttonBuscarPorNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBuscarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBuscarPorNumero)
                    .addComponent(buttonBuscarTodos)
                    .addComponent(textFieldNumeroAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tableLocacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Cliente", "CPF", "Habilitação", "Marca", "Modelo", "Placa", "Valor Locação", "Data Locação", "Data Devolução"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableLocacoes.getTableHeader().setReorderingAllowed(false);
        tableLocacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLocacoesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableLocacoes);
        if (tableLocacoes.getColumnModel().getColumnCount() > 0) {
            tableLocacoes.getColumnModel().getColumn(0).setResizable(false);
            tableLocacoes.getColumnModel().getColumn(1).setResizable(false);
            tableLocacoes.getColumnModel().getColumn(2).setResizable(false);
            tableLocacoes.getColumnModel().getColumn(3).setResizable(false);
            tableLocacoes.getColumnModel().getColumn(4).setResizable(false);
            tableLocacoes.getColumnModel().getColumn(5).setResizable(false);
            tableLocacoes.getColumnModel().getColumn(7).setResizable(false);
            tableLocacoes.getColumnModel().getColumn(8).setResizable(false);
            tableLocacoes.getColumnModel().getColumn(9).setResizable(false);
        }

        buttonFinalizarLocacao.setText("Finalizar Locação");
        buttonFinalizarLocacao.setEnabled(false);
        buttonFinalizarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinalizarLocacaoActionPerformed(evt);
            }
        });

        buttonCalcularMulta.setText("Calcular Multa");
        buttonCalcularMulta.setEnabled(false);
        buttonCalcularMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalcularMultaActionPerformed(evt);
            }
        });

        buttonGerarNotaFiscal.setText("Gerar Nota Fiscal");
        buttonGerarNotaFiscal.setEnabled(false);
        buttonGerarNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGerarNotaFiscalActionPerformed(evt);
            }
        });

        buttonSair.setText("Sair");
        buttonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonFinalizarLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCalcularMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonGerarNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFinalizarLocacao)
                    .addComponent(buttonCalcularMulta)
                    .addComponent(buttonGerarNotaFiscal)
                    .addComponent(buttonSair))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBuscarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarTodosActionPerformed
        limparTabela();
        textFieldNumeroAluguel.setText("");

        ArrayList<AluguelBean> lista = AluguelDao.getTodosAlugueis();

        DefaultTableModel modelo = (DefaultTableModel) tableLocacoes.getModel();

        if (!lista.isEmpty()) {

            for (int i = 0; i < lista.size(); i++) {

                modelo.addRow(lista.get(i).getAluguelo());

            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma Locação Cadastrada!", "ATENÇÃO!", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBuscarTodosActionPerformed

    private void buttonBuscarPorNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarPorNumeroActionPerformed
        limparTabela();
        if (textFieldNumeroAluguel.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o número da Locação!");
            textFieldNumeroAluguel.requestFocus(true);
        } else {
            AluguelBean aluguel = AluguelDao.getAluguel(Double.parseDouble(textFieldNumeroAluguel.getText()));
            DefaultTableModel modelo = (DefaultTableModel) tableLocacoes.getModel();
            if (aluguel != null) {
                modelo.addRow(aluguel.getAluguelo());
            } else {
                JOptionPane.showMessageDialog(null, "Locação Inexistente!\n Não foi possível encontrar a locação especificado!", "Atenção", JOptionPane.ERROR_MESSAGE);
            }

    }//GEN-LAST:event_buttonBuscarPorNumeroActionPerformed
    }
    private void buttonFinalizarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinalizarLocacaoActionPerformed
        int linha = tableLocacoes.getSelectedRow();
        double numero = ((Double) tableLocacoes.getModel().getValueAt(linha, 0));
        aluguel = AluguelDao.getAluguel(numero);
        aluguel.getAutomovel().Devolver();
        automovel = aluguel.getAutomovel();
        AutomovelDao.atualizarAutomovel(automovel);
        AluguelDao.ConfirmaDevolucao(aluguel.getNumero());
        JOptionPane.showMessageDialog(null, "Locação Finalizada com Sucesso!!!");
        limparTabela();
        buttonFinalizarLocacao.setEnabled(false);
        buttonCalcularMulta.setEnabled(false);
        buttonGerarNotaFiscal.setEnabled(false);
    }//GEN-LAST:event_buttonFinalizarLocacaoActionPerformed

    private void buttonCalcularMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalcularMultaActionPerformed
        int linha = tableLocacoes.getSelectedRow();
        double numero = ((Double) tableLocacoes.getModel().getValueAt(linha, 0));
        aluguel = AluguelDao.getAluguel(numero);
        Date hoje = new Date();
        aluguel.diasMulta(aluguel.getDatadevolucao(), hoje);
        aluguel.calcularMulta();
        if (aluguel.getMulta() <= 0) {
            JOptionPane.showMessageDialog(null, "Não existe Multa para esta locação!!!");
        } else {
            JOptionPane.showMessageDialog(null, "Valor da Multa: " + aluguel.getMulta());
        }
    }//GEN-LAST:event_buttonCalcularMultaActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tableLocacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLocacoesMouseClicked
        if (tableLocacoes.getSelectedRow() != -1) {
            buttonFinalizarLocacao.setEnabled(true);
            buttonCalcularMulta.setEnabled(true);
            buttonGerarNotaFiscal.setEnabled(true);
        } else {
            JOptionPane.showConfirmDialog(null, "Selecione uma Locação!");

        }        // TODO add your handling code here:
    }//GEN-LAST:event_tableLocacoesMouseClicked

    private void buttonGerarNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGerarNotaFiscalActionPerformed
        FormNotaFiscal fnf = new FormNotaFiscal();
        fnf.setVisible(true);
        int linha = tableLocacoes.getSelectedRow();
        double numero = ((Double) tableLocacoes.getModel().getValueAt(linha, 0));
        aluguel = AluguelDao.getAluguel(numero);
        FormNotaFiscal.aluguel = aluguel;
    }//GEN-LAST:event_buttonGerarNotaFiscalActionPerformed

    private void buttonSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSairMouseClicked
        this.dispose();
    }//GEN-LAST:event_buttonSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConsultaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConsultaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConsultaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConsultaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConsultaLocacao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscarPorNumero;
    private javax.swing.JButton buttonBuscarTodos;
    private javax.swing.JButton buttonCalcularMulta;
    private javax.swing.JButton buttonFinalizarLocacao;
    private javax.swing.JButton buttonGerarNotaFiscal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLocacoes;
    private javax.swing.JTextField textFieldNumeroAluguel;
    // End of variables declaration//GEN-END:variables

    private void limparTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tableLocacoes.getModel();
        for (int i = tableLocacoes.getRowCount() - 1; i >= 0; --i) {
            modelo.removeRow(i);
        }

    }

}
